### PR TITLE
Check if Node.js process satisfies min version

### LINKED ISSUE #200: Warn user about not supported Node version
# Context

CLI doesn't work on Node `<16` and we decided not to support lower versions. We must be sure our users are aware of it and CLI handles gracefully not supported environment

# Proposed solution

1. Check the existing node version (`node -v`) and compare it to `engines` field in `package.json`
2. Print (on red!) there is a version mismatch each time CLI is spawned

### PR DESCRIPTION
**Pull request by zaiste**
Fixes #200

### CODE REVIEW

**Review by 2can — APPROVED** [review]

File: src/cli.ts [hunk 1]
```diff
@@ -42,6 +43,13 @@ import { useTelemetry } from './middleware/index.js';
 const require = createRequire(import.meta.url);
 const pkg = require('../package.json');
 
+if (!semver.satisfies(process.versions.node, pkg.engines.node)) {
+  console.error(
+    `${chalk.red('ERROR')}: Saleor CLI requires Node.js 16.x or later`
```
Comment (lkostrowski) [inline src/cli.ts:48]: @zaiste version shouldn't be hardcoded here, node version is specified in package, so it should print the same as `engines.node` contains
